name: Update README

on:
  schedule:
    - cron: '* 2 * * *'
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [14, 16]
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.version }}

    - name: Install Dependencies
      run: npm install

    - name: Call Process
      run: node ./manual/process.js

    - name: Merge
      run: mv readme.dev.md README.md

    - name: Push Newest
      run: |
        git config --global user.name 'Github Action'
        git config --global user.email 'action@github.com'
        git commit -am "Updated"
        git push
